name: CI
on: [push, pull_request]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        node-version: ['14', '12', '10']
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']
    runs-on: ${{ matrix.os }}
    name: Node ${{ matrix.node-version }} sample (${{ matrix.os }})
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache NPM
        id: cache-node-modules
        uses: actions/cache@v2
        env:
          cache-name: node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-

      - name: Install NPM Dependencies
        run: npm ci

      - name: Setup Python for Github-Markup
        if: ${{ runner.os != 'Windows' }}
        uses: actions/setup-python@v2
        with:
          python-version: '2.x'

      - name: Install docutils for Github-Markup
        if: ${{ runner.os != 'Windows' }}
        run: |
          python -m pip install --upgrade pip
          pip install docutils

      - name: Setup Licensee, Linguist, and Github-Markup Dependencies (MacOS)
        if: ${{ runner.os == 'macOS' }}
        run: brew install cmake pkg-config icu4c libidn

      - name: Setup Licensee, Linguist, and Github-Markup Dependencies (Linux)
        if: ${{ runner.os == 'Linux' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libicu-dev libcurl4-openssl-dev libldap2-dev libidn11-dev

      - name: Setup Ruby
        if: ${{ runner.os != 'Windows' }}
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'

      - name: Cache Ruby Gems
        if: ${{ runner.os != 'Windows' }}
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install Ruby Dependencies
        if: ${{ runner.os != 'Windows' }}
        run: |
          gem install --no-document bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Run Test
        if: ${{ runner.os != 'Windows' }}
        run: bundle exec npm test

      - name: Run Test (Windows)
        if: ${{ runner.os == 'Windows' }}
        run: npm test

  test-docker:
    runs-on: ubuntu-latest
    name: Docker sample
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Build
        uses: docker/build-push-action@v2
        with:
          tags: todogroup/repolinter:latest
          load: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Docker Run
        run: docker run -t -v ${{ github.workspace }}:/src -w /src todogroup/repolinter:latest .

  publish-to-ghcr:
    name: Push Docker image to GitHub Container Registry
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [test, test-docker]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Gather Docker Metadata
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@55d3462 #v1.9.1
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and Push to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
